// ข้อความของแดชบอร์ดผู้สอน (ข้อความระบบ ไม่ใช่เนื้อหาบทเรียน เนื้อหาบทเรียนอ่านจาก course.json เท่านั้น)
export const t = {
  title: "แดชบอร์ดผู้สอน",
  subtitle: "AI Trainer Quest",
  login: {
    password: "รหัสผ่านครู",
    classCode: "รหัสห้องเรียน (เว้นว่าง = ทุกห้อง)",
    submit: "เข้าสู่แดชบอร์ด",
    loading: "กำลังโหลด…",
    wrong_password: "รหัสผ่านไม่ถูกต้อง",
    bad_class_code: "รหัสห้องเรียนใช้ได้เฉพาะตัวอักษรอังกฤษ ตัวเลข และขีด ไม่เกิน 20 ตัว",
    not_configured: "ยังไม่ได้ตั้งค่า TEACHER_PASSWORD บนเซิร์ฟเวอร์ (อย่างน้อย 8 ตัวอักษร) ดูขั้นตอนใน README.md",
    no_database: "ยังไม่ได้ตั้งค่า SUPABASE_URL และ SUPABASE_SERVICE_ROLE_KEY บนเซิร์ฟเวอร์ ดูขั้นตอนใน README.md",
    failed: "โหลดข้อมูลไม่ได้ ({reason}) ลองใหม่อีกครั้ง",
    demo: "ดูตัวอย่างจากข้อมูลในเครื่องนี้",
    demoNote: "ตัวอย่าง: แสดงเฉพาะความคืบหน้าที่บันทึกในเบราว์เซอร์เครื่องนี้ ไม่ใช่ข้อมูลของทั้งห้อง",
    demoEmpty: "เครื่องนี้ยังไม่มีความคืบหน้าที่บันทึกไว้",
    game: "ไปหน้าเกม",
  },
  toolbar: {
    refresh: "โหลดใหม่",
    logout: "ออกจากระบบ",
    showArchived: "รวมข้อมูลที่ผู้เรียนเริ่มใหม่ (เก็บถาวร)",
    allClasses: "ทุกห้อง",
    classFilter: "ห้องเรียน",
    loadedAt: "ข้อมูล ณ {time}",
    deleteClass: "ลบข้อมูลห้องนี้",
    deletePrompt: "ลบข้อมูลของห้อง {code} ทั้งหมด {n} รายการอย่างถาวร ส่งออก CSV เก็บไว้ก่อนหรือยัง\nพิมพ์รหัสห้องเรียนเพื่อยืนยัน",
    deleted: "ลบแล้ว {n} รายการ",
  },
  tabs: { students: "นักเรียน", rooms: "สรุปรายห้อง", gain: "ก่อนเรียน–หลังเรียน" },
  cards: {
    students: "ผู้เรียน",
    finished: "จบครบ 6 ห้อง",
    pre: "ก่อนเรียน (เฉลี่ย)",
    post: "หลังเรียน (เฉลี่ย)",
    gain: "พัฒนาการ (เฉลี่ย)",
    normalized: "พัฒนาการสัมพัทธ์",
    paired: "ทำครบทั้งสองครั้ง {n} คน",
    accuracy: "Accuracy ภาคสนาม (เฉลี่ย)",
    tutor: "ถามพี่บิต (AI / คำใบ้)",
  },
  students: {
    empty: "ยังไม่มีผู้เรียนในห้องนี้ ผู้เรียนต้องใส่รหัสห้องเรียนตอนลงทะเบียนในเกม ข้อมูลจึงจะมาที่นี่",
    name: "ชื่อที่แสดง",
    classCode: "ห้อง",
    difficulty: "แมพ",
    difficultyNames: { easy: "แมพ 1", normal: "แมพ 2", hard: "แมพ 3" },
    room: "เรื่องที่ถึง",
    cores: "แกน AI",
    stars: "ดาวเควส",
    review: "ทบทวน",
    battles: "ปราบไคจู",
    accuracy: "Accuracy ภาคสนาม",
    pre: "ก่อน",
    post: "หลัง",
    gain: "พัฒนาการ",
    tutor: "ถามพี่บิต",
    time: "เวลา (นาที)",
    updated: "ล่าสุด",
    archived: "เก็บถาวร",
    details: "ดูรายละเอียด",
    hide: "ซ่อน",
    answers: "คำถามทบทวนแบบเลือกตอบ: จำนวนข้อที่ตอบถูกตั้งแต่ครั้งแรก (ไม่ใช่คะแนนเก็บ เกมไม่มีการเขียนตอบแล้ว)",
    noAnswers: "ยังไม่มีผลคำถามทบทวน",
    resumeCode: "รหัสเล่นต่อจากเครื่องอื่น",
    fieldPending: "ยังไม่ส่ง",
    roomLabel: "ห้อง {n}",
    sortHint: "กดหัวตารางเพื่อเรียงลำดับ",
  },
  rooms: {
    room: "ห้อง",
    entered: "เข้าแล้ว",
    finished: "ได้แกน AI",
    time: "เวลาเฉลี่ย (นาที)",
    stars: "ดาวเฉลี่ย",
    tutorAi: "ถาม AI",
    tutorHints: "คำใบ้สำเร็จรูป",
    repairs: "ถูกส่งเข้าห้องซ่อม",
    missed: "ชิ้นที่ตอบผิดมากที่สุดในเควส",
    missedCount: "{count} ครั้ง · {students} คน",
    noMissed: "ยังไม่มีข้อมูลการตอบผิด",
    note: "เวลานับเฉพาะตอนเปิดหน้าเกมและยังกดเล่นอยู่ ห้อง 6 ไม่รวมเวลาที่ไปทำใน Teachable Machine",
  },
  gain: {
    byTopic: "พัฒนาการรายสมรรถนะ (เฉพาะผู้เรียนที่ทำครบทั้งสองครั้ง)",
    topic: "สมรรถนะ",
    n: "จำนวนคน",
    pre: "ก่อนเรียน (เฉลี่ย)",
    post: "หลังเรียน (เฉลี่ย)",
    gain: "พัฒนาการ",
    total: "รวมทั้งฉบับ",
    byItem: "รายข้อ",
    item: "ข้อ",
    form: "ชุด",
    content: "สิ่งที่ถาม",
    preShare: "ตอบถูกก่อนเรียน",
    postShare: "ตอบถูกหลังเรียน",
    difference: "ผลต่าง",
    note: "ผู้เรียนแต่ละคนทำชุด A และชุด B คนละครั้ง (สุ่มว่าชุดไหนก่อน) รายข้อจึงเทียบผู้เรียนคนละกลุ่ม ใช้ดูแนวโน้ม ส่วนรายสมรรถนะเทียบคนเดียวกันก่อนและหลัง",
    noData: "ยังไม่มีผู้เรียนที่ทำแบบทดสอบ",
  },
  export: {
    students: "ส่งออก CSV นักเรียน",
    items: "ส่งออก CSV รายข้อ",
  },
  csv: {
    students: ["class_code", "display_name", "archived", "updated_at", "map", "topic_reached", "ai_cores", "quest_stars", "reviews_done", "field_accuracy_percent", "field_done", "pretest_form", "pre_total", "post_total", "gain", "normalized_gain", "tutor_ai", "tutor_hints", "forced_repairs", "minutes_total", "kaiju_defeated", "kaiju_total", "battle_answers", "battle_correct", "side_activities_done"],
    pre: "pre_topic",
    post: "post_topic",
    stars: "stars_room",
    minutes: "minutes_room",
    items: ["item_id", "form", "topic", "pre_n", "pre_correct_share", "post_n", "post_correct_share", "difference"],
  },
} as const;
